import { type Config } from "tailwindcss";
import { fontFamily } from "tailwindcss/defaultTheme";

export default {
  content: ["./src/**/*.tsx"],
  theme: {
    extend: {
      colors: {
        classicGreen: {
          primary: "#013A20",
          secondary: "#478C5C",
          accentOne: "#BACC81",
          accentTwo: "#CDD193"
        },
        light: {
          primary: "#FFFFFF",
          secondary: "#478C5C",
          accentOne: "#013A20",
          accentTwo: "#002917"
        },
        purpleMoonlight: {
          primary: "#121212",
          secondary: "#332940",
          accentOne: "#D4BFF9",
          accentTwo: "#BB86FC"
        },
        pink: {
            primary: "#F2789F",
            secondary: "#F999B7",
            accentOne: "#F9C5D5",
            accentTwo: "#FEE3EC"
        }
      },
      fontFamily: {
        sans: ["var(--font-sans)", ...fontFamily.sans],
      },
    },
  },
  safelist: [
    "bg-classicGreen-primary",
    "text-classicGreen-primary",
    "border-classicGreen-primary",
    "hover:bg-classicGreen-primary",
    "hover:text-classicGreen-primary",
    "hover:border-classicGreen-primary",
    "focus:bg-classicGreen-primary",
    "focus:text-classicGreen-primary",
    "focus:border-classicGreen-primary",
    "focus:ring-classicGreen-primary",
    "placeholder-classicGreen-primary",
    "active:bg-classicGreen-primary",
    "active:text-classicGreen-primary",
    "active:border-classicGreen-primary",
    "disabled:bg-classicGreen-primary",
    "disabled:text-classicGreen-primary",
    "disabled:border-classicGreen-primary",
    "bg-classicGreen-secondary",
    "text-classicGreen-secondary",
    "border-classicGreen-secondary",
    "hover:bg-classicGreen-secondary",
    "hover:text-classicGreen-secondary",
    "hover:border-classicGreen-secondary",
    "focus:bg-classicGreen-secondary",
    "focus:text-classicGreen-secondary",
    "focus:border-classicGreen-secondary",
    "focus:ring-classicGreen-secondary",
    "placeholder-classicGreen-secondary",
    "active:bg-classicGreen-secondary",
    "active:text-classicGreen-secondary",
    "active:border-classicGreen-secondary",
    "disabled:bg-classicGreen-secondary",
    "disabled:text-classicGreen-secondary",
    "disabled:border-classicGreen-secondary",
    "bg-classicGreen-accentOne",
    "text-classicGreen-accentOne",
    "border-classicGreen-accentOne",
    "hover:bg-classicGreen-accentOne",
    "hover:text-classicGreen-accentOne",
    "hover:border-classicGreen-accentOne",
    "focus:bg-classicGreen-accentOne",
    "focus:text-classicGreen-accentOne",
    "focus:border-classicGreen-accentOne",
    "focus:ring-classicGreen-accentOne",
    "placeholder-classicGreen-accentOne",
    "active:bg-classicGreen-accentOne",
    "active:text-classicGreen-accentOne",
    "active:border-classicGreen-accentOne",
    "disabled:bg-classicGreen-accentOne",
    "disabled:text-classicGreen-accentOne",
    "disabled:border-classicGreen-accentOne",
    "bg-classicGreen-accentTwo",
    "text-classicGreen-accentTwo",
    "border-classicGreen-accentTwo",
    "hover:bg-classicGreen-accentTwo",
    "hover:text-classicGreen-accentTwo",
    "hover:border-classicGreen-accentTwo",
    "focus:bg-classicGreen-accentTwo",
    "focus:text-classicGreen-accentTwo",
    "focus:border-classicGreen-accentTwo",
    "focus:ring-classicGreen-accentTwo",
    "placeholder-classicGreen-accentTwo",
    "active:bg-classicGreen-accentTwo",
    "active:text-classicGreen-accentTwo",
    "active:border-classicGreen-accentTwo",
    "disabled:bg-classicGreen-accentTwo",
    "disabled:text-classicGreen-accentTwo",
    "disabled:border-classicGreen-accentTwo",
    "bg-light-primary",
    "text-light-primary",
    "border-light-primary",
    "hover:bg-light-primary",
    "hover:text-light-primary",
    "hover:border-light-primary",
    "focus:bg-light-primary",
    "focus:text-light-primary",
    "focus:border-light-primary",
    "focus:ring-light-primary",
    "placeholder-light-primary",
    "active:bg-light-primary",
    "active:text-light-primary",
    "active:border-light-primary",
    "disabled:bg-light-primary",
    "disabled:text-light-primary",
    "disabled:border-light-primary",
    "bg-light-secondary",
    "text-light-secondary",
    "border-light-secondary",
    "hover:bg-light-secondary",
    "hover:text-light-secondary",
    "hover:border-light-secondary",
    "focus:bg-light-secondary",
    "focus:text-light-secondary",
    "focus:border-light-secondary",
    "focus:ring-light-secondary",
    "placeholder-light-secondary",
    "active:bg-light-secondary",
    "active:text-light-secondary",
    "active:border-light-secondary",
    "disabled:bg-light-secondary",
    "disabled:text-light-secondary",
    "disabled:border-light-secondary",
    "bg-light-accentOne",
    "text-light-accentOne",
    "border-light-accentOne",
    "hover:bg-light-accentOne",
    "hover:text-light-accentOne",
    "hover:border-light-accentOne",
    "focus:bg-light-accentOne",
    "focus:text-light-accentOne",
    "focus:border-light-accentOne",
    "focus:ring-light-accentOne",
    "placeholder-light-accentOne",
    "active:bg-light-accentOne",
    "active:text-light-accentOne",
    "active:border-light-accentOne",
    "disabled:bg-light-accentOne",
    "disabled:text-light-accentOne",
    "disabled:border-light-accentOne",
    "bg-light-accentTwo",
    "text-light-accentTwo",
    "border-light-accentTwo",
    "hover:bg-light-accentTwo",
    "hover:text-light-accentTwo",
    "hover:border-light-accentTwo",
    "focus:bg-light-accentTwo",
    "focus:text-light-accentTwo",
    "focus:border-light-accentTwo",
    "focus:ring-light-accentTwo",
    "placeholder-light-accentTwo",
    "active:bg-light-accentTwo",
    "active:text-light-accentTwo",
    "active:border-light-accentTwo",
    "disabled:bg-light-accentTwo",
    "disabled:text-light-accentTwo",
    "disabled:border-light-accentTwo",
    "bg-purpleMoonlight-primary",
    "text-purpleMoonlight-primary",
    "border-purpleMoonlight-primary",
    "hover:bg-purpleMoonlight-primary",
    "hover:text-purpleMoonlight-primary",
    "hover:border-purpleMoonlight-primary",
    "focus:bg-purpleMoonlight-primary",
    "focus:text-purpleMoonlight-primary",
    "focus:border-purpleMoonlight-primary",
    "focus:ring-purpleMoonlight-primary",
    "placeholder-purpleMoonlight-primary",
    "active:bg-purpleMoonlight-primary",
    "active:text-purpleMoonlight-primary",
    "active:border-purpleMoonlight-primary",
    "disabled:bg-purpleMoonlight-primary",
    "disabled:text-purpleMoonlight-primary",
    "disabled:border-purpleMoonlight-primary",
    "bg-purpleMoonlight-secondary",
    "text-purpleMoonlight-secondary",
    "border-purpleMoonlight-secondary",
    "hover:bg-purpleMoonlight-secondary",
    "hover:text-purpleMoonlight-secondary",
    "hover:border-purpleMoonlight-secondary",
    "focus:bg-purpleMoonlight-secondary",
    "focus:text-purpleMoonlight-secondary",
    "focus:border-purpleMoonlight-secondary",
    "focus:ring-purpleMoonlight-secondary",
    "placeholder-purpleMoonlight-secondary",
    "active:bg-purpleMoonlight-secondary",
    "active:text-purpleMoonlight-secondary",
    "active:border-purpleMoonlight-secondary",
    "disabled:bg-purpleMoonlight-secondary",
    "disabled:text-purpleMoonlight-secondary",
    "disabled:border-purpleMoonlight-secondary",
    "bg-purpleMoonlight-accentOne",
    "text-purpleMoonlight-accentOne",
    "border-purpleMoonlight-accentOne",
    "hover:bg-purpleMoonlight-accentOne",
    "hover:text-purpleMoonlight-accentOne",
    "hover:border-purpleMoonlight-accentOne",
    "focus:bg-purpleMoonlight-accentOne",
    "focus:text-purpleMoonlight-accentOne",
    "focus:border-purpleMoonlight-accentOne",
    "focus:ring-purpleMoonlight-accentOne",
    "placeholder-purpleMoonlight-accentOne",
    "active:bg-purpleMoonlight-accentOne",
    "active:text-purpleMoonlight-accentOne",
    "active:border-purpleMoonlight-accentOne",
    "disabled:bg-purpleMoonlight-accentOne",
    "disabled:text-purpleMoonlight-accentOne",
    "disabled:border-purpleMoonlight-accentOne",
    "bg-purpleMoonlight-accentTwo",
    "text-purpleMoonlight-accentTwo",
    "border-purpleMoonlight-accentTwo",
    "hover:bg-purpleMoonlight-accentTwo",
    "hover:text-purpleMoonlight-accentTwo",
    "hover:border-purpleMoonlight-accentTwo",
    "focus:bg-purpleMoonlight-accentTwo",
    "focus:text-purpleMoonlight-accentTwo",
    "focus:border-purpleMoonlight-accentTwo",
    "focus:ring-purpleMoonlight-accentTwo",
    "placeholder-purpleMoonlight-accentTwo",
    "active:bg-purpleMoonlight-accentTwo",
    "active:text-purpleMoonlight-accentTwo",
    "active:border-purpleMoonlight-accentTwo",
    "disabled:bg-purpleMoonlight-accentTwo",
    "disabled:text-purpleMoonlight-accentTwo",
    "disabled:border-purpleMoonlight-accentTwo",
    "bg-pink-primary",
    "text-pink-primary",
    "border-pink-primary",
    "hover:bg-pink-primary",
    "hover:text-pink-primary",
    "hover:border-pink-primary",
    "focus:bg-pink-primary",
    "focus:text-pink-primary",
    "focus:border-pink-primary",
    "focus:ring-pink-primary",
    "placeholder-pink-primary",
    "active:bg-pink-primary",
    "active:text-pink-primary",
    "active:border-pink-primary",
    "disabled:bg-pink-primary",
    "disabled:text-pink-primary",
    "disabled:border-pink-primary",
    "bg-pink-secondary",
    "text-pink-secondary",
    "border-pink-secondary",
    "hover:bg-pink-secondary",
    "hover:text-pink-secondary",
    "hover:border-pink-secondary",
    "focus:bg-pink-secondary",
    "focus:text-pink-secondary",
    "focus:border-pink-secondary",
    "focus:ring-pink-secondary",
    "placeholder-pink-secondary",
    "active:bg-pink-secondary",
    "active:text-pink-secondary",
    "active:border-pink-secondary",
    "disabled:bg-pink-secondary",
    "disabled:text-pink-secondary",
    "disabled:border-pink-secondary",
    "bg-pink-accentOne",
    "text-pink-accentOne",
    "border-pink-accentOne",
    "hover:bg-pink-accentOne",
    "hover:text-pink-accentOne",
    "hover:border-pink-accentOne",
    "focus:bg-pink-accentOne",
    "focus:text-pink-accentOne",
    "focus:border-pink-accentOne",
    "focus:ring-pink-accentOne",
    "placeholder-pink-accentOne",
    "active:bg-pink-accentOne",
    "active:text-pink-accentOne",
    "active:border-pink-accentOne",
    "disabled:bg-pink-accentOne",
    "disabled:text-pink-accentOne",
    "disabled:border-pink-accentOne",
    "bg-pink-accentTwo",
    "text-pink-accentTwo",
    "border-pink-accentTwo",
    "hover:bg-pink-accentTwo",
    "hover:text-pink-accentTwo",
    "hover:border-pink-accentTwo",
    "focus:bg-pink-accentTwo",
    "focus:text-pink-accentTwo",
    "focus:border-pink-accentTwo",
    "focus:ring-pink-accentTwo",
    "placeholder-pink-accentTwo",
    "active:bg-pink-accentTwo",
    "active:text-pink-accentTwo",
    "active:border-pink-accentTwo",
    "disabled:bg-pink-accentTwo",
    "disabled:text-pink-accentTwo",
    "disabled:border-pink-accentTwo"
  ],
  plugins: [],
} satisfies Config;
