import Head from "next/head";
import {UserButton, useUser} from "@clerk/nextjs";

import {api} from "~/utils/api";

export default function Home() {
    const hello = api.foodDiary.getFoodDiaryEntry.useQuery({id: "0d94035b-f5d7-4ab7-9c89-bf5129db1568"})
    const user = useUser();

    const handleButtonClick = () => {
        console.log(hello);
    };

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main
                className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
                    {!!user.isSignedIn && "hello"}
                    <UserButton afterSignOutUrl="/"/>
                    <button onClick={handleButtonClick} className="px-4 py-2 bg-blue-500 text-white rounded">
                        Log Hello
                    </button>
                </div>
            </main>
        </>
    );
}
